# Generated by Django 6.0.2 on 2026-06-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('allow_superuser', models.BooleanField(default=True)),
                ('allow_admin', models.BooleanField(default=True)),
                ('allow_manager', models.BooleanField(default=False)),
                ('allow_employee', models.BooleanField(default=False)),
            ],
        ),
    ]
